#!/usr/bin/python


from mininet.net import Mininet
from mininet.log import setLogLevel, info
from mininet.cli import CLI
from mininet.node import Controller
import sys

def assign32():

    "Create an empty network and add nodes to it."
    args=(sys.argv)
    hostCount=int(args[1])
    switchCount=int(args[2])

    print "no of hosts : "+args[1]
    print "no of swithes : "+args[2]

    net = Mininet( controller=Controller )

    info( '*** Adding controller\n' )
    net.addController( 'c0' )

    info( '*** Adding hosts\n' )
    hosts=[]

    for i in range(hostCount):
	hosts.append(net.addHost('h'+str(i+1)))

    info( '*** Adding switch\n' )
    switches=[]

    for i in range(switchCount):
	switches.append(net.addSwitch('s'+str(i+1)))

    info( '*** Creating links\n' )
    for switchIndex in range(switchCount):
	if switchIndex+2 < switchCount:
		net.addLink(switches[switchIndex],switches[switchIndex+2])
	if switchIndex%2 == 0 :
		net.addLink(switches[switchIndex],hosts[2*switchIndex])
		net.addLink(switches[switchIndex],hosts[2*switchIndex+2])
	else:
		net.addLink(switches[switchIndex],hosts[2*switchIndex-1])
		net.addLink(switches[switchIndex],hosts[2*switchIndex+1])

    info( '*** Starting network\n')
    net.start()

    info( '*** Running CLI\n' )
    CLI( net )

    info( '*** Stopping network' )
    net.stop()

if __name__ == '__main__':
    setLogLevel( 'info' )
    assign32()
